stages:
  - build
  - codeception
  - sonarqube
  - deploy

codeception-check:
  stage: codeception
  image:  innosabi/php:8.2-dev
  cache:
    - key:
        files:
          - composer.lock
      paths:
        - vendor/
  allow_failure: true
  artifacts:
    untracked: true
    expire_in: 1 day
    paths:
      - tests/_output
  before_script:
    # Install all project dependencies
    - composer install
  rules:
    - if: $CI_COMMIT_BRANCH == 'devel'
  script:
    - echo "Running Codeception ..."
    - vendor/bin/codecept run --coverage --coverage-xml --xml coverage.clover
    - ls tests/_output/

sonarqube-check:
  stage: sonarqube
  image:
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [ "" ]
  needs:
    - job: codeception-check
      artifacts: true
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  script:
    - ls tests/_output/
    - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.projectKey="${SONAR_PROJECT_KEY}" -Dsonar.sources=src/ -Dsonar.tests=tests/ -Dsonar.php.coverage.reportPaths=tests/_output/coverage.xml
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'devel'
